name: Build Test APK

on:
  workflow_dispatch:
  push:
    branches: [ release ]

jobs:
  build-test-apk:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: setup Java (for Android build only)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: setup Android SDK (for Android build only)
        uses: android-actions/setup-android@v3

      - name: install NDK (for Android build only)
        run: sdkmanager "ndk;27.0.11902837"

      - name: install dependencies
        run: pnpm install

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - uses: Swatinem/rust-cache@v2
        with:
          key: ubuntu-latest-android-cargo

      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./frontend/package.json').version")" >> $GITHUB_ENV

      - name: build Android Release APKs
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/27.0.11902837
        run: |
          cd backend
          # 清理之前的构建
          rm -rf src-tauri/gen/android
          
          # 初始化 Android 项目
          pnpm tauri android init
          
          # 生成图标
          pnpm tauri icon backend/src-tauri/icons/icon.png
          
          # 恢复 git 状态
          git checkout .

          # 添加权限到 AndroidManifest.xml
          MANIFEST="src-tauri/gen/android/app/src/main/AndroidManifest.xml"
          PERMISSION_LINE='<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>'
          grep -q 'REQUEST_INSTALL_PACKAGES' "$MANIFEST" || \
            sed -i "/android.permission.INTERNET/a \    $PERMISSION_LINE" "$MANIFEST"


          # 签名
          pushd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

          # 输出一下 secrets.ANDROID_KEY_ALIAS
          echo "ANDROID_KEY_ALIAS: ${ANDROID_KEY_ALIAS}"
          echo "ANDROID_KEY_PASSWORD: ${ANDROID_KEY_PASSWORD}"
          echo "ANDROID_KEY_BASE64: ${ANDROID_KEY_BASE64}"
    

          popd
          version=$PACKAGE_VERSION
          
          # 构建 universal release APK
          pnpm tauri android build
          universal_apk=spanishassistant_${version}_universal.apk
          cp src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk $universal_apk
          
          # 构建 arm64 release APK
          pnpm tauri android build -t aarch64
          arm64_apk=spanishassistant_${version}_arm64.apk
          cp src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk $arm64_apk

          echo "Built APK files:"
          ls -la *.apk

      - name: Upload release APKs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apks
          path: backend/*.apk
          retention-days: 30


